SELECT * FROM TABS;

SELECT * FROM EMP; --14행
SELECT * FROM DEPT; --4행


SELECT * FROM EMP, DEPT; -- 14*4 = 56행


-- 등가 조인

SELECT *
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;


--변수명뿐 아니라 테이블명에도 별칭을 쓸 수 있다
SELECT *
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.SAL>=3000;

SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
  WHERE E.SAL<=2500
    AND E.EMPNO <=9999
  ORDER BY E.EMPNO;
  
SELECT * 
  FROM EMP E, SALGRADE S
  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
  
SELECT * FROM SALGRADE;



--셀프조인 자체조인 : 하나의 테이블(자신)을 대상으로 조인하는 것

SELECT * FROM EMP;

--EMP 테이블을 다시 EMP테이블과 중복으로 조인하게 되면 조인에 참여하는 특성명이 같아지는 문제가 생김
--이 떄는 별칭(ALIAS)을 사용

--EMP STAFF, EMP MANAGER 이런 식으로 쓰면 됨

--예) 사원 BLAKE(사원번호 7698) 가 관리하는 부하사원의 이름과 직급을 출력하시오.
SELECT STAFF.ENAME, STAFF.JOB
  FROM EMP STAFF, EMP MANAGER
  WHERE STAFF.MGR = MANAGER.EMPNO
    AND MANAGER.ENAME LIKE 'BLAKE';


--LEFT OUTER JOIN

SELECT E1. EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.NAME AS MGT_ENAME
FROM EMP ET, EMPP E2
WHERE S1.MGT(+) = E2.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
FROM EMP E NATURAL JOIN DEPT D
ORDER BY DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING (DEPTNO)
ORDER BY DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY E.DEPTNO, EMPNO;



--쿼리

SELECT *
FROM EMP
WHERE COMM>(SELECT COMM
            FROM EMP
            WHERE ENAME = 'ALLEN');
            

--실행 결과가 하나인 단일행 서브쿼리 (교재 P246)
SELECT *
    FROM EMP
  WHERE HIREDATE < (SELECT HIREDATE
                      FROM EMP
                      WHERE ENAME = 'SCOTT';


